# Default values for imagepullsecret-controller
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

clusterName: master
prometheus:
  apiAddresses:
    - http://prometheus:9090
  queryAddress: http://prometheus:9090
  directQueryAddress: http://prometheus:9090

replicas: 1

istio:
  revision: ""

podAnnotations: []

podSecurityContext:
  runAsUser: 65534
  runAsGroup: 65534
securityContext:
  allowPrivilegeEscalation: false
image:
  repository: banzaicloud/imagepullsecrets
  tag: master
  pullPolicy: IfNotPresent
  pullSecrets:
    needed: false
    dockerConfig: |
      {}
nodeSelector: {}
affinity: {}
tolerations: []
resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "200Mi"
    cpu: "300m"

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  annotations: {}

serviceMonitor:
  scrapeInterval: 5s
  tlsConfig: {}

developmentMode:
  enabled: false

podDisruptionBudget:
  enabled: false

log:
  {}
  # level: info # accepted values: panic, fatal, error, warn, warning, info, debug, trace

defaultConfig:
  enabled: true
  targetSecretName: default-secret-name
  namespaces: {}
  namespacesWithPods: []
  credentials: []
