---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "imagepullsecret-controller.fullname" . }}-pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imagepullsecret-controller.labels" . | nindent 4 }}
stringData:
  .dockerconfigjson: |
      {
        "auths":
          {
            "{{ .Values.registry.url }}":{
                  "username":"{{ .Values.registry.user }}",
                  "password":"{{ .Values.registry.password }}",
                  "auth":"{{ join "" (list .Values.registry.user ":" .Values.registry.password) | b64enc }}"
            }
          }
      }
# TODO!
type: kubernetes.io/dockerconfigjson
