{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "imagepullsecret-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imagepullsecret-controller.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "imagepullsecret-controller.selectorLabels" . | nindent 6 }}
{{- end }}
