apiVersion: v1
kind: Service
metadata:
  name: {{ include "imagepullsecret-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imagepullsecret-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "imagepullsecret-controller.selectorLabels" . | nindent 4 }}
