# Copyright (c) 2019 Banzai Cloud Zrt. All Rights Reserved.

# Build the manager binary
FROM golang:1.15 as builder

ARG GOPROXY

ENV GOFLAGS="-mod=readonly"

WORKDIR /workspace/
# Copy the Go Modules manifests

COPY ./go.mod /workspace/
COPY ./go.sum /workspace/
RUN go mod download

COPY ./ /workspace/

# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o manager ./cmd/refresher/

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM alpine:3.13.4

RUN apk add --update --no-cache ca-certificates

WORKDIR /
COPY --from=builder /workspace/manager .
USER nobody:nobody

ENTRYPOINT ["/manager"]
