approved = [
  "mit",
  "apache-2.0",
  "bsd-3-clause",
  "bsd-2-clause",
  "mpl-2.0",
]

ignored = [
  "github.com/davecgh/go-spew", # ISC license
  "github.com/gogo/protobuf",
  "google.golang.org/protobuf",  
  "github.com/ghodss/yaml",
  "sigs.k8s.io/yaml", # Forked from above
  "gopkg.in/fsnotify.v1",

  "github.com/banzaicloud/backyards",
  "github.com/banzaicloud/backyards/services/sre",
  "github.com/banzaicloud/backyards/pkg/platform/log",
  "github.com/banzaicloud/backyards/pkg/prometheus",
  "github.com/banzaicloud/backyards/pkg/common",
  "github.com/banzaicloud/backyards/pkg/template",
]
