{{- if .Values.defaultConfig.enabled }}
---
apiVersion: images.banzaicloud.io/v1alpha1
kind: ImagePullSecret
metadata:
  name: {{ include "imagepullsecret-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "imagepullsecret-controller.labels" . | nindent 4 }}
spec:
  registry:
    target:
      secret:
        targetSecretName: {{ .Values.defaultConfig.name }}
        {{- with .Values.defaultConfig.namespaces }}
        namespaces:
        {{ . | toYaml 10 }}
        {{- end }}
        {{- with .Values.defaultConfig.namespacesWithPods }}
        namespacesWithPods:
        {{ . | toYaml 10 }}
        {{- end }}
    credentials:
      namespace: {{ .Release.Namespace }}
      name: {{ include "imagepullsecret-controller.fullname" . }}-pull-secret

{{- end }}
