{{ if .Values.image.pullSecrets.needed }}
# TODO: on operator side implement that if the provisioned imps CR exists and it has been updated in the last 20 minutes
# then remove this secret!
{{ if not .Values.defaultConfig.targetSecretName }}
{{ fail "defaultConfig is needed when image pull secrets are required"}}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.defaultConfig.targetSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imagepullsecret-controller.labels" . | nindent 4 }}
stringData:
  .dockerconfigjson: "{{ .Values.image.pullSecrets.dockerConfig }}"
type: kubernetes.io/dockerconfigjson
{{ end }}
