# Default values for imagepullsecret-controller
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

clusterName: master
prometheus:
  apiAddresses:
    - http://prometheus:9090
  queryAddress: http://prometheus:9090
  directQueryAddress: http://prometheus:9090

# TODO: align deployment
replicas: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

istio:
  revision: ""

podAnnotations: []

podSecurityContext:
  runAsUser: 65534
  runAsGroup: 65534
securityContext:
  allowPrivilegeEscalation: false
image:
  repository: ghcr.io/banzaicloud/imagepullsecrets
  tag: latest
  pullPolicy: IfNotPresent
nodeSelector: {}
affinity: {}
tolerations: {}
resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "200Mi"
    cpu: "300m"

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  annotations: {}

serviceMonitor:
  scrapeInterval: 5s
  tlsConfig: {}

# TODO: support
developmentMode:
  enabled: false

podDisruptionBudget:
  enabled: false
# operatorVersion:

log:
  {}
  # level: info # accepted values: panic, fatal, error, warn, warning, info, debug, trace

registry:
  user: a
  password: b
  # TODO: make this configurable via the CLI
  url: "https://index.docker.io/v1/"

# TODO: add option to provision imps
