{{- if .Values.defaultSecret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "imagepullsecret-controller.fullname" . }}-default
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imagepullsecret-controller.labels" . | nindent 4 }}
type: {{ .Values.defaultSecret.type }}
stringData:
    {{- with .Values.defaultSecret.stringData }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
