name: Docker

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-dev.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

env:
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Determine tag or commit
        uses: haya14busa/action-cond@v1
        id: refortag
        with:
          cond: ${{ startsWith(github.ref, 'refs/tags/') }}
          if_true: ${{ github.ref }}
          if_false: latest
      - name: Determine image tag
        id: imagetag
        run: echo "value=${TAG_OR_BRANCH##*/}" >> $GITHUB_OUTPUT
        env:
          TAG_OR_BRANCH: ${{ steps.refortag.outputs.value }}
      - name: Build imagepullsecrets refresher
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile-refresher
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            ghcr.io/banzaicloud/imagepullsecrets-refresher:${{ steps.imagetag.outputs.value }}
      - name: Build imagepullsecrets refresher with Red Hat UBI base image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile-refresher
          # Red Hat UBI doesn't support linux/arm/v7
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            FROM_IMAGE=redhat/ubi8-micro:8.7
          tags: |
            ghcr.io/banzaicloud/imagepullsecrets-refresher-rh-ubi8:${{ steps.imagetag.outputs.value }}
